<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AssemblyName>Winova.NetworkService</AssemblyName>
    <Version>0.1.22</Version>
    <RootNamespace>Winova.NetworkService</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>
</Project>
